[package]
name = "nvcore"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[profile.dev]
debug = "full"
panic = "abort"

[profile.release]
panic = "abort"
debug = "full"
codegen-units = 1
lto = true
opt-level = 3

[workspace]
members = ["crates/loadefi","crates/nvcvm"]

[dependencies]
paste = "1.0.15"
nvcvm = {path = "crates/nvcvm"}
spin = "0.10.0"
log = "0.4.27"

[dependencies.portable-dlmalloc]
version = "0.3.2"
features = ["alt-alloc"]

[dependencies.iced-x86]
version = "1.21.0"
default-features = false
features = ["no_std","decoder","op_code_info","instr_info","masm"]
