[package]
name = "nvcore"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
debug = true

[workspace]
members = ["tools/nvdebug"]

[dependencies]
paste = "1.0.15"

[dependencies.portable-dlmalloc]
version = "0.2.1"
features = []

[dependencies.iced-x86]
version = "1.21.0"
default-features = false
features = ["no_std","decoder","op_code_info","instr_info","masm"]

[build-dependencies]
cc = "1.0.46"
