[package]
name = "nvcvm"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "NoirVisor Customizable Virtual Machine (CVM) Library for User Hypervisors"
homepage = "https://github.com/Zero-Tang/NoirVisor"
repository = "https://github.com/Zero-Tang/NoirVisor"
readme = "readme.md"
keywords = ["no_std","hypervisor","vmm"]
categories = ["no-std","virtualization"]

[dependencies]
bitfield-struct = "0.13.0"
paste = "1.0.15"

[features]
# User-hypervisor should use this feature.
user = []
# Kernel scheduler should use this feature.
kernel = []
# Only NoirVisor may use this feature.
hypervisor = []
default = ["kernel"]

[target.'cfg(target_os="uefi")'.dependencies]
r-efi = "*"
